baseURL: https://hackerunder.dev
languageCode: en-us
title: Hacker Under Dev
theme: hackerunderdev
googleAnalytics: G-PXSHHWH5LB

SectionPagesMenu: main

params:
  ananke_socials:
    - name: github
      url: https://github.com/Greenjam94/HackerUnderDev
    - name: mastodon
      url: https://infosec.exchange/@Greenjam94