baseURL: https://hackerunder.dev
languageCode: en-us
title: Hacker Under Dev
theme: hackerunderdev
googleAnalytics: G-PXSHHWH5LB

SectionPagesMenu: main

params:
  ananke_socials:
    - name: twitter
      url: https://twitter.com/hackerunderdev
    - name: github
      url: https://github.com/Greenjam94/HackerUnderDev
